name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: shard77
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_repositories: yes
          plugin_repositories_featured: Athena-OS/athena-iso
          plugin_repositories_order: featured, pinned, starred, random
          plugin_topics: yes
          
